-- Produto 
CREATE TABLE PRODUTO (
   IDPRODUTO NUMERIC(18,0),
   CODIGO NUMERIC(8),
   CODIGOBARRAS VARCHAR(30),
   DESCRICAO VARCHAR(250),
   PRECO NUMERIC(7,2),
   IDCATEGORIA NUMERIC(18,0),
   IDFORNECEDOR NUMERIC(18,0),
   IDMARCA NUMERIC(18,0),
   
   PRIMARY KEY (IDPRODUTO),
   FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA),
   FOREIGN KEY (IDFORNECEDOR)REFERENCES FORNECEDOR(IDFORNECEDOR),
   FOREIGN KEY (IDMARCA) REFERENCES MARCA(IDMARCA)
);
CREATE SEQUENCE IDPRODUTO START 1
SELECT NEXTVAL('IDPRODUTO');
ALTER SEQUENCE IDPRODUTO RESTART 1;

SELECT * FROM PRODUTO;


-- Categoria 
CREATE TABLE CATEGORIA(
   IDCATEGORIA NUMERIC(18,0),
   CODIGO NUMERIC(10),
   DESCRICAO VARCHAR(150),

   PRIMARY KEY (IDCATEGORIA)
);
CREATE SEQUENCE IDCATEGORIA START 1;
SELECT NEXTVAL('IDCATEGORIA');
ALTER SEQUENCE IDPRODUTO RESTART 1;

SELECT * FROM CATEGORIA;


-- Fornecedor
CREATE TABLE FORNECEDOR(
   IDFORNECEDOR NUMERIC(18,0),
   CODIGO NUMERIC(10),
   DESCRICAO VARCHAR(150),

   PRIMARY KEY (IDFORNECEDOR)
);
CREATE SEQUENCE IDFORNECEDOR START 1;
SELECT NEXTVAL ('IDFORNECEDOR');
ALTER SEQUENCE IDFORNECEDOR RESTART 1;

SELECT * FROM FORNECEDOR;


-- Marca
CREATE TABLE MARCA(
   IDMARCA NUMERIC(18,0),
   CODIGO NUMERIC(10),
   DESCRICAO VARCHAR(150),

   PRIMARY KEY (IDMARCA)
);
CREATE SEQUENCE IDMARCA START 1;
SELECT NEXTVAL ('IDMARCA');
ALTER SEQUENCE IDMARCA RESTART 1;

SELECT * FROM MARCA;


-- Email
CREATE TABLE EMAIL(
  IDEMAIL NUMERIC(18,0),
  ASSUNTO VARCHAR(100),
  DESTINATARIO VARCHAR(100),
  MENSAGEM VARCHAR(250)
);
CREATE SEQUENCE IDMARCA START 1;
SELECT NEXTVAL ('IDMARCA');
ALTER SEQUENCE IDMARCA RESTART 1;

SELECT * FROM EMAIL;

-- Configurador Email
CREATE TABLE CONFIGURADOREMAIL(
   HOST VARCHAR(50),
   PORT NUMERIC(3,0),
   REMETENTE VARCHAR(150),
   SENHAREMETENTE VARCHAR(150)
);

SELECT * FROM CONFIGURADOREMAIL;